spring.application.name=osdrmsa-appl

#Server Port
server.port=8080

#Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:oracleDB
spring.datasource.username=rcosd
spring.datasource.password=Changeme0
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver


spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true